### ISSUE TITLE
Breaks URL replacement

### ISSUE THREAD

**Issue by minchinweb** [JenkinsDev/pelican-readtime#4]
Using this plug in seems to break everywhere I use the `{filename}` notation to link to another file. The actual error message is:

```
WARNING: Unable to find `images/2006/mail.png`, skipping url replacement.
```

Oddly, this error isn't displayed when the `post_stats` plugin (from the pelican-plugins repo) is active as well.

My guess is this is somehow related to/can be solved by https://github.com/getpelican/pelican/pull/1616

**Comment by viktorbengtsson** [comment]
Can confirm this behaviour.

Created a pull request to fix this. #5
